version: '3'

services:
  pgdatabase:
    image: postgres:14
    container_name: pg-database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5433:5432
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"